# Generated by Django 4.2.14 on 2024-08-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_owner_alter_employee_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Не начат"), (2, "Начат"), (3, "Закончен")],
                default=1,
            ),
        ),
    ]
