# Generated by Django 4.2.14 on 2024-08-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_started_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.AddField(
            model_name="project",
            name="teams",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.team",
            ),
        ),
    ]
