# Generated by Django 4.2.14 on 2024-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_remove_project_team_project_teams"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="unique_member"
            ),
        ),
    ]
