# Generated by Django 4.2.14 on 2024-08-06 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_member_unique_member"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "default_related_name": "teams",
                "ordering": ("name",),
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
    ]
