# Generated by Django 4.2.14 on 2024-08-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0004_alter_employee_options_alter_employee_parent_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employee",
            name="unique_parent",
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                check=models.Q(("id", models.F("parent")), _negated=True),
                name="unique_parent",
            ),
        ),
    ]
