# Generated by Django 4.2.14 on 2024-08-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0005_remove_employee_unique_parent_employee_unique_parent",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Должность"
            ),
        ),
    ]
