# Generated by Django 4.2.14 on 2024-08-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_remove_project_teams_projectteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                related_name="projects", to="projects.projectteam"
            ),
        ),
    ]
