# Generated by Django 4.2.14 on 2024-08-04 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_employee_project_alter_employee_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
    ]
