# Generated by Django 4.2.14 on 2024-08-06 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0007_project_teams"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectteam",
            options={
                "default_related_name": "project_team",
                "verbose_name": "Проект-команда",
                "verbose_name_plural": "Проекты-команды",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
            preserve_default=False,
        ),
    ]
