# Generated by Django 4.2.14 on 2024-08-09 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_projectteam_options_team_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="teams",
        ),
    ]
