# Generated by Django 4.2.14 on 2024-08-10 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_project_teams"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={
                "default_related_name": "members",
                "verbose_name": "Участник",
                "verbose_name_plural": "Участники",
            },
        ),
    ]
