# Generated by Django 4.2.14 on 2024-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_alter_member_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=150,
                unique=True,
                verbose_name="Отдел",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название"
            ),
        ),
    ]
