# Generated by Django 4.2.14 on 2024-08-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Город"
            ),
        ),
    ]
