# Generated by Django 4.2.14 on 2024-07-31 11:50

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", apps.users.managers.CustomUserManager()),
            ],
        ),
    ]
