# Generated by Django 4.2.14 on 2024-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=150,
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=150,
                verbose_name="Отчество",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, max_length=25, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="position",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Должность",
            ),
        ),
    ]
