# Generated by Django 4.2.14 on 2024-08-01 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_middle_name_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="images/users/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator("^8\\d{10}$")
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
