# Generated by Django 4.2.14 on 2024-08-01 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_first_name_customuser_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="images/users/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
