# Generated by Django 4.2.14 on 2024-08-01 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_profile_image_customuser_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="О себе"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="images/users/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg"]
                    )
                ],
                verbose_name="Аватар",
            ),
        ),
    ]
