# Generated by Django 4.2.14 on 2024-08-02 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_profile_options_profile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                blank=True, null=True, verbose_name="День рождения"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="time_zone",
            field=models.SmallIntegerField(
                blank=True,
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(-12),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Часовой пояс",
            ),
        ),
    ]
