# Generated by Django 4.2.14 on 2024-08-02 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_profile_birthday_profile_position_profile_time_zone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="position",
        ),
    ]
