# Generated by Django 4.2.14 on 2024-08-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_profile_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Должность"
            ),
        ),
    ]
