[tool.isort]
profile = "black"
line_length = 79
combine_as_imports = true
include_trailing_comma = true
remove_redundant_aliases = true
skip_glob = ["**/migrations/*.py"]
src_paths = ["src/backend"]
no_lines_before = ["LOCALFOLDER"]
lines_after_imports=2

[tool.black]
line-length = 79
target-version = ['py311']
extend-exclude = """
    settings/*.py
    | migrations
"""
