version: '3.3'

volumes:
  pg_data:
  staticfiles:
  mediafiles:

services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: mxnoob/gazprom_backend
    env_file: .env
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: mxnoob/gazprom_frontend
    command: cp -r /app/dist/. /frontend_static/
    volumes:
      - staticfiles:/frontend_static

  nginx:
    image: mxnoob/gazprom_nginx
    ports:
      - "8000:80"
    volumes:
      - staticfiles:/staticfiles/
      - mediafiles:/media/
    depends_on:
      - frontend
      - backend

  redis:
    image: redis:7.4-rc2-alpine
